import streamlit as st

# ---------------------------------------------------
# PAGE CONFIGURATION
# ---------------------------------------------------

st.set_page_config(
    page_title="Alhassan Health Consultant",
    page_icon="🩺",
    layout="wide",
    initial_sidebar_state="expanded"
)

# ---------------------------------------------------
# CUSTOM STYLING
# ---------------------------------------------------

st.markdown("""
<style>

.main {
    background-color: #f8fafc;
}

h1 {
    color: #0f172a;
    font-weight: 800;
}

h2, h3 {
    color: #1e293b;
}

.stAlert {
    border-radius: 12px;
}

.hero-box {
    background: linear-gradient(
        135deg,
        #0f172a,
        #1e3a8a
    );
    padding: 3rem;
    border-radius: 20px;
    color: white;
    text-align: center;
    margin-bottom: 2rem;
}

.info-card {
    background-color: white;
    padding: 1.5rem;
    border-radius: 18px;
    box-shadow: 0px 4px 15px rgba(0,0,0,0.08);
    margin-bottom: 1rem;
}

.footer {
    text-align: center;
    color: gray;
    margin-top: 3rem;
    padding: 1rem;
}

</style>
""", unsafe_allow_html=True)

# ---------------------------------------------------
# SIDEBAR
# ---------------------------------------------------

st.sidebar.image(
    "https://cdn-icons-png.flaticon.com/512/2966/2966486.png",
    width=120
)

st.sidebar.title("🩺 Navigation")

st.sidebar.info("""
Use the sidebar to access:

• Weight Assessment  
• BMI Evaluation  
• BP Risk Assessment  
""")

st.sidebar.success("AI-Powered Health Screening")

# ---------------------------------------------------
# HERO SECTION
# ---------------------------------------------------

st.markdown("""
<div class="hero-box">

<h1>🩺 Alhassan Health Consultant</h1>

<h3>
Smart Health Screening & Predictive Analytics Platform
</h3>

<p>
A machine learning powered healthcare application designed
to provide fast preliminary health assessments using
predictive models.
</p>

</div>
""", unsafe_allow_html=True)

# ---------------------------------------------------
# MAIN CONTENT
# ---------------------------------------------------

col1, col2 = st.columns(2)

with col1:

    st.markdown("""
    <div class="info-card">

    <h3>📊 BMI Evaluation</h3>

    <p>
    Analyze body mass index using patient
    demographic and physical measurements.
    </p>

    </div>
    """, unsafe_allow_html=True)

    st.markdown("""
    <div class="info-card">

    <h3>⚖️ Weight Assessment</h3>

    <p>
    Predict estimated body height and evaluate
    weight-related health indicators.
    </p>

    </div>
    """, unsafe_allow_html=True)

with col2:

    st.markdown("""
    <div class="info-card">

    <h3>❤️ BP Risk Assessment</h3>

    <p>
    Predict blood pressure risk category using
    lifestyle and physiological indicators.
    </p>

    </div>
    """, unsafe_allow_html=True)

    st.markdown("""
    <div class="info-card">

    <h3>🤖 Machine Learning Models</h3>

    <p>
    Powered by Scikit-Learn predictive models
    with standardized preprocessing pipelines.
    </p>

    </div>
    """, unsafe_allow_html=True)

# ---------------------------------------------------
# INFORMATION SECTION
# ---------------------------------------------------

st.markdown("## 🔍 About This System")

st.write("""
The Alhassan Health Consultant platform is an AI-assisted
healthcare screening application developed for educational,
research, and preliminary assessment purposes.

The application integrates machine learning techniques
to evaluate health indicators such as:

- Body Mass Index (BMI)
- Blood Pressure (BP) Risk
- Weight and Height Relationships

This platform is intended to support awareness and
early health screening, but it does not replace
professional medical diagnosis or treatment.
""")

# ---------------------------------------------------
# DISCLAIMER
# ---------------------------------------------------

st.warning("""
⚠️ DISCLAIMER:
This application is intended strictly for educational,
research, and preliminary screening purposes only.
Predictions generated by this system should not be used
as a substitute for professional medical advice,
diagnosis, or treatment.
""")

# ---------------------------------------------------
# FOOTER
# ---------------------------------------------------

st.markdown("""
<div class="footer">

Developed by <b>Alhassan Health Analytics Lab</b><br>

Powered by Streamlit & Scikit-Learn

</div>
""", unsafe_allow_html=True)
